name: Create Artifact

on: push

env: 
  ARTIFACT_NAME: artifactName
  
jobs: 
  build:
    name: create-artifact
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: ./${{ env.ARTIFACT_NAME }}.exe
