name: Create Artifact

on: push

env: 
  ARTIFACT_NAME: artifactName
  
jobs: 
  build:
    name: create-artifact
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3.5.2

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: actions/checkout@v3.5.2
        path: .
